# Generated by Django 3.1.4 on 2020-12-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201229_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='long_name',
            new_name='longname',
        ),
    ]
