# Generated by Django 3.1.4 on 2021-01-08 00:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
