# Generated by Django 3.1.5 on 2021-02-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210127_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitiondate',
            old_name='falling_to_rising',
            new_name='rising_phase',
        ),
        migrations.RemoveField(
            model_name='transitiondate',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='transitiondate',
            name='obj_created',
        ),
        migrations.AddField(
            model_name='transitiondate',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
