# Generated by Django 3.1.5 on 2021-02-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210203_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitiondate',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
