# Generated by Django 3.1.5 on 2021-02-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210204_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='dominant_species',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='site',
            name='elevation',
            field=models.IntegerField(default=0),
        ),
    ]
